[package]
name = "spark"
version = "0.12.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"

[lib]
name = "spark"
path = "src/lib.rs"

[[bin]]
name = "sparkc"
path = "src/bin/sparkc.rs"


[dependencies]
bitflags = "1.3" # Used to store attributes of AST nodes 
thiserror = "1.0" # Easier creation of custom error types
arrayvec = "0.7" # Stack allocated vector types to improve performance


[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"] } # For benchmarking performance of compiler

[[bench]]
name = "lexer"
path = "benches/lexer.rs"
harness = false

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false

[profile.release]
codegen-units = 1
# lto = true
panic = 'abort'


[profile.bench]
lto = true
codegen-units = 1