[package]
name = "spark"
version = "0.12.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"

[lib]
name = "spark"
path = "src/lib.rs"

[[bin]]
name = "sparkc"
path = "src/bin/sparkc.rs"


[dependencies]
bitflags = "1.3" # Used to store attributes of AST nodes
smallvec = "1.7" # Stack / heap allocated vector types to improve performance
string-interner = "0.14" # Interning symbol strings
num-bigint = "0.4" # Big integers for number literals
quickscope = "0.1" # ScopeMap
hashbrown = "0.11" # Non-secure fast hashmap

cranelift = "0.79" # Code generation backend
cranelift-module = "0.79" # Code generation
cranelift-object = "0.79"

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"] } # For benchmarking performance of compiler

[[bench]]
name = "lexer"


[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false

[profile.release]
codegen-units = 1
# lto = true
panic = 'abort'


[profile.bench]
lto = true
codegen-units = 1
