[package]
name = "sparkc"
version = "0.12.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"

[dependencies]


[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"] } # For benchmarking performance of compiler

[[bench]]
name = "lexer"
path = "benches/lexer.rs"
harness = false

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false

[profile.release]
codegen-units = 1
# lto = true
panic = 'abort'


[profile.bench]
lto = true
codegen-units = 1