[package]
name = "sparkc"
version = "0.8.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33" # For command line arguments
console = "0.14" # For command line styling
thiserror = "1.0" # For error handling

log = { version = "0.4" } # For logging in the compiler
fern = "0.6" # For logging in the compiler

hashbrown = "0.11.2" # For mapping strings to values throughout the compiler
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] } # For actual code generation
utf8-chars = "1" # For reading a BufReader character by character without reading entire file to string
bitflags = "1.2" # For function and variable attributes

bumpalo = "3.7" # Bump arena allocator for namespaces
semver = "1.0" # Finding the highest LINK.exe version on windows

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"] } # For benchmarking performance of compiler

[[bench]]
name = "lexical"
path = "benches/lexical.rs"
harness = false

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false

[profile.release]
codegen-units = 1
# lto = true
panic = 'abort'


[profile.bench]
lto = true
codegen-units = 1