[package]
name = "spark"
version = "0.1.0"
authors = ["Bendi11 <bkliebmann@gmail.com>"]
edition = "2018"


[dependencies]
hashbrown = "0.11.2" # For mapping strings to values throughout the compiler

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"] } # For benchmarking performance of compiler

[[bench]]
name = "lexical"
path = "benches/lexical.rs"
harness = false

[[bench]]
name = "parser"
path = "benches/parse.rs"
harness = false

[profile.bench]
lto = true
codegen-units = 1